/* eslint-disable */
/**
 * Generated API.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@0.14.1.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type { ApiFromModules } from "convex/api";
import type * as getDogSummary from "../getDogSummary";
import type * as getDogs from "../getDogs";
import type * as http from "../http";
import type * as saveTypeformResponse from "../saveTypeformResponse";
import type * as storeUser from "../storeUser";

/**
 * A type describing your app's public Convex API.
 *
 * This `API` type includes information about the arguments and return
 * types of your app's query and mutation functions.
 *
 * This type should be used with type-parameterized classes like
 * `ConvexReactClient` to create app-specific types.
 */
export type API = ApiFromModules<{
  getDogSummary: typeof getDogSummary;
  getDogs: typeof getDogs;
  http: typeof http;
  saveTypeformResponse: typeof saveTypeformResponse;
  storeUser: typeof storeUser;
}>;
