/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@0.17.0.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type { ApiFromModules } from "convex/server";
import type * as app from "../app";
import type * as authenticateTypeformWebhook from "../authenticateTypeformWebhook";
import type * as http from "../http";
import type * as storeUser from "../storeUser";
import type * as typeform from "../typeform";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: ApiFromModules<{
  app: typeof app;
  authenticateTypeformWebhook: typeof authenticateTypeformWebhook;
  http: typeof http;
  storeUser: typeof storeUser;
  typeform: typeof typeform;
}>;
